In [1]:
# from sklearn.datasets import load_boston
import numpy as np
import pandas as pd

In [5]:
!pip install kagglehub

Collecting kagglehub
  Downloading kagglehub-1.0.2-py3-none-any.whl.metadata (40 kB)
Collecting kagglesdk<1.0,>=0.1.22 (from kagglehub)
  Downloading kagglesdk-0.1.37-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\moham\appdata\roaming\python\python314\site-packages (from kagglehub) (26.0)
Collecting pyyaml (from kagglehub)
  Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl.metadata (2.4 kB)
Requirement already satisfied: requests in c:\users\moham\appdata\local\programs\python\python314\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\moham\appdata\local\programs\python\python314\lib\site-packages (from kagglehub) (4.70.0)
Requirement already satisfied: protobuf in c:\users\moham\appdata\local\programs\python\python314\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (7.35.1)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\moham\appdata\local\programs\python\python314\lib\site-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\moham\appdata\local\programs\python\python314\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\moham\appdata\local\programs\python\python314\lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\moham\appdata\local\programs\python\python314\lib\site-packages (from requests->kagglehub) (2026.1.4)
Requirement already satisfied: colorama in c:\users\moham\appdata\roaming\python\python314\site-packages (from tqdm->kagglehub) (0.4.6)
Downloading kagglehub-1.0.2-py3-none-any.whl (70 kB)
Downloading kagglesdk-0.1.37-py3-none-any.whl (262 kB)
Downloading pyyaml-6.0.3-cp314-cp314-win_amd64.whl (156 kB)
Installing collected packages: pyyaml, kagglesdk, kagglehub

   ---------------------------------------- 0/3 [pyyaml]
   ---------------------------------------- 0/3 [pyyaml]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   ------------- -------------------------- 1/3 [kagglesdk]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   -------------------------- ------------- 2/3 [kagglehub]
   ---------------------------------------- 3/3 [kagglehub]

Successfully installed kagglehub-1.0.2 kagglesdk-0.1.37 pyyaml-6.0.3

[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("altavish/boston-housing-dataset")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\moham\.cache\kagglehub\datasets\altavish\boston-housing-dataset\versions\1

In [4]:
import os
print(os.listdir(path))

['HousingData.csv']

In [5]:
df = pd.read_csv(os.path.join(path, 'HousingData.csv'))
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [6]:
df = df.fillna(df.mean(numeric_only=True))

In [7]:
X = df.drop(columns='MEDV').values
y = df['MEDV'].values

In [8]:
X.shape

(506, 13)

In [9]:
y.shape

(506,)

In [10]:
X

array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]], shape=(506, 13))

In [11]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.model_selection import cross_val_score

In [12]:
lr = LinearRegression()
dt = DecisionTreeRegressor()
svr = SVR()

In [13]:
estimators = [('lr',lr),('dt',dt),('svr',svr)]

In [14]:
for estimator in estimators:
  scores = cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
  print(estimator[0],np.round(np.mean(scores),2))

lr 0.19
dt -0.17
svr -0.42

In [15]:
from sklearn.ensemble import VotingRegressor

In [16]:
vr = VotingRegressor(estimators)
scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
print("Voting Regressor",np.round(np.mean(scores),2))

Voting Regressor 0.43

In [17]:
for i in range(1,4):
  for j in range(1,4):
    for k in range(1,4):
      vr = VotingRegressor(estimators,weights=[i,j,k])
      scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
      print("For i={},j={},k={}".format(i,j,k),np.round(np.mean(scores),2))

For i=1,j=1,k=1 0.44
For i=1,j=1,k=2 0.35
For i=1,j=1,k=3 0.27
For i=1,j=2,k=1 0.41
For i=1,j=2,k=2 0.39
For i=1,j=2,k=3 0.31
For i=1,j=3,k=1 0.38
For i=1,j=3,k=2 0.39
For i=1,j=3,k=3 0.36
For i=2,j=1,k=1 0.44
For i=2,j=1,k=2 0.41
For i=2,j=1,k=3 0.34
For i=2,j=2,k=1 0.43
For i=2,j=2,k=2 0.42
For i=2,j=2,k=3 0.4
For i=2,j=3,k=1 0.41
For i=2,j=3,k=2 0.42
For i=2,j=3,k=3 0.4
For i=3,j=1,k=1 0.42
For i=3,j=1,k=2 0.42
For i=3,j=1,k=3 0.37
For i=3,j=2,k=1 0.44
For i=3,j=2,k=2 0.43
For i=3,j=2,k=3 0.43
For i=3,j=3,k=1 0.41
For i=3,j=3,k=2 0.44
For i=3,j=3,k=3 0.44

In [18]:
model_vc = VotingRegressor(estimators=estimators,weights=[2,1,1])
x = cross_val_score(
    estimator=model_vc,
    X = X,
    y = y,
    cv=10,
    scoring='r2'
)
print(np.round(np.mean(x),2))

0.45

In [19]:
# using the same algorithm

dt1 = DecisionTreeRegressor(max_depth=1)
dt2 = DecisionTreeRegressor(max_depth=3)
dt3 = DecisionTreeRegressor(max_depth=5)
dt4 = DecisionTreeRegressor(max_depth=7)
dt5 = DecisionTreeRegressor(max_depth=None)

In [20]:
estimators = [('dt1',dt1),('dt2',dt2),('dt3',dt3),('dt4',dt4),('dt5',dt5)]

In [21]:
for estimator in estimators:
  scores = cross_val_score(estimator[1],X,y,scoring='r2',cv=10)
  print(estimator[0],np.round(np.mean(scores),2))

dt1 -0.51
dt2 0.02
dt3 0.05
dt4 -0.0
dt5 -0.12

In [22]:
vr = VotingRegressor(estimators)
scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
print("Voting Regressor",np.round(np.mean(scores),2))

Voting Regressor 0.26

In [23]:
Score = []

for i in range(1,4):
    for j in range(1,4):
        for k in range(1,4):
            for l in range(1,4):
                for m in range(1,4):

                    vr = VotingRegressor(
                        estimators,
                        weights=[i,j,k,l,m]
                    )

                    scores = cross_val_score(
                        vr, X, y,
                        scoring='r2',
                        cv=10
                    )

                    Score.append([
                        i,
                        j,
                        k,
                        l,
                        m,
                        np.round(np.mean(scores), 2)
                    ])

In [24]:
cross_val_value_data = pd.DataFrame(Score,columns=['i','j','k','l','m','score'])

In [25]:
np.max(cross_val_value_data['score'])

np.float64(0.33)

In [27]:
cross_val_value_data[cross_val_value_data['score'] == 0.33]

     i  j  k  l  m  score
97   2  1  2  3  2   0.33
223  3  3  1  3  2   0.33

In [29]:
vr = VotingRegressor(estimators,weights=[3,3,1,3,2])
scores = cross_val_score(vr,X,y,scoring='r2',cv=10)
print("Voting Regressor",np.round(np.mean(scores),3))

Voting Regressor 0.305