In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
df = pd.read_csv('play_tennis.csv')

In [4]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [5]:
# Problem 1

# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or No Play?

# Solution

# P(Yes | Sunny,Hot,High,Weak)=P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes)

# P(No | Sunny,Hot,High,Weak)=P(Sunny | No) * P(Hot | No) * P(High | No) * P(Weak | No)

# Compare and decide using the Maximum a posteriori rule

In [6]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [7]:
p_play_y = 9/14
p_play_n = 5/14

In [8]:
pd.crosstab(df['outlook'],df['play'])

play      No  Yes
outlook
Overcast   0    4
Rain       2    3
Sunny      3    2

In [9]:
# Probability of outlook wrt play 
p_outlook_overcast_n = 0
p_outlook_rain_n = 2/5
p_outlook_sunny_n = 3/5

p_outlook_overcast_y = 4/9
p_outlook_rain_y = 3/9
p_outlook_sunny_y = 2/9

In [10]:
# probability of temp
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [11]:
p_temp_cool_n = 1/5
p_temp_hot_n = 2/5
p_temp_mid_n = 2/5

p_temp_cool_y =  3/9
p_temp_hot_y = 2/9
p_temp_mid_y = 4/9

In [12]:
#probability of humidity 
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [13]:
p_hum_high_n = 4/5
p_hum_nor_n = 1/5

p_hum_high_y = 3/9
p_hum_nor_y = 6/9

In [14]:
# probability of wind
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [15]:
p_strong_wind_n = 3/5
p_weak_wind_n = 2/5

p_strong_wind_y = 3/9
p_weak_wind_y = 6/9

In [16]:
# Problem 1

# Outlook=Sunny, Temp=Hot, Humidity=High, Wind=Weak
# Play or No Play?

# sol:
#  P(Yes | Sunny,Hot,High,Weak)=P(Sunny | Yes) * P(Hot | Yes) * P(High | Yes) * P(Weak | Yes)*p(yes)
p_yes_play = p_outlook_sunny_y * p_temp_hot_y * p_hum_high_y * p_weak_wind_y * p_play_y
p_no_play= p_outlook_sunny_n * p_temp_hot_n * p_hum_high_n * p_weak_wind_n * p_play_n

if p_yes_play > p_no_play:
    print("Yes tennis match can be play that day")

else:
    print("NO tennis match cannot be play that day due to unconditional weather")

NO tennis match cannot be play that day due to unconditional weather

In [17]:
print(p_yes_play)
print(p_no_play)

0.007054673721340387
0.02742857142857143

    using Sklearn

In [24]:
df.head()

  day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [23]:
X = df.drop(columns=['day','play'])
y = df['play']

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import accuracy_score,r2_score,classification_report

In [27]:
encoder = OrdinalEncoder()
X = encoder.fit_transform(X)

In [30]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [31]:
model = CategoricalNB()
model.fit(X_train,y_train)

CategoricalNB()

In [35]:
y_test

11    Yes
4     Yes
5      No
Name: play, dtype: str

In [37]:
y_pred = model.predict(X_test)
y_pred

array(['Yes', 'Yes', 'Yes'], dtype='<U3')

In [ ]:
accuracy_score(y_test,y_pred)

0.6666666666666666

: